export const REGULAR_RUNS = [
    {
        id: 'kokyo',
        citySlug: 'tokyo',
        name: '皇居ラン',
        place: '皇居',
        day: '毎週水曜',
        dayShort: '水曜',
        dayOfWeek: 3,
        time: '06:00〜',
        timeRaw: '06:00',
        meetingPlace: '桔梗門前派出所',
        meetingShort: '桔梗門派出所前',
        distance: '約5km',
        pace: '会話できるペース（1km 6〜7分台が目安）',
        host: 'HINODE運営メンバー',
        photography: '参加者の撮影なし',
        firstJoin: '開始5分前に集合場所へ。背中に「HINODE」と書かれた黒いTシャツを着た運営メンバーが目印です。',
        image: '/assets/Kokyo.jpg',
        scheduleHref: '/schedule#kokyo',
        detailHref: '/locations/kokyo',
    },
    {
        id: 'meguro',
        citySlug: 'tokyo',
        name: '目黒川ラン',
        place: '目黒川',
        day: '毎週木曜',
        dayShort: '木曜',
        dayOfWeek: 4,
        time: '06:00〜',
        timeRaw: '06:00',
        meetingPlace: 'スターバックス 中目黒蔦屋書店前',
        meetingShort: '中目黒駅スタバ前',
        distance: '約4km',
        pace: '会話できるペース（1km 6〜7分台が目安）',
        host: 'HINODE運営メンバー',
        photography: '参加者の撮影なし',
        firstJoin: '開始5分前に集合場所へ。背中に「HINODE」と書かれた黒いTシャツを着た運営メンバーが目印です。',
        image: '/assets/Meguro.jpg',
        scheduleHref: '/schedule#meguro',
        detailHref: '/locations/meguro',
    },
    {
        id: 'yoyogi',
        citySlug: 'tokyo',
        name: '代々木公園ラン',
        place: '代々木公園',
        day: '毎週日曜',
        dayShort: '日曜',
        dayOfWeek: 0,
        time: '07:15〜',
        timeRaw: '07:15',
        meetingPlace: '原宿時計塔前',
        meetingShort: '原宿時計塔前',
        distance: '約2〜4km',
        pace: '会話できるペース（1km 6〜7分台が目安）',
        host: 'HINODE運営メンバー',
        photography: '参加者の撮影なし',
        firstJoin: '開始5分前に集合場所へ。背中に「HINODE」と書かれた黒いTシャツを着た運営メンバーが目印です。',
        image: '/assets/Yoyogi.jpg',
        scheduleHref: '/schedule#yoyogi',
        detailHref: '/locations/yoyogi',
        recommendationLabel: '初参加におすすめ',
        isFirstChoice: true,
    },
];

export function getRegularRun(id) {
    return REGULAR_RUNS.find((run) => run.id === id);
}

export const FIRST_CHOICE_RUN = REGULAR_RUNS.find((run) => run.isFirstChoice);
